repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    - id: flake8

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.6.0
    hooks:
    -   id: pylint

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 9feadeb
  hooks:
  - id: mypy
    args: [--ignore-missing-imports, --warn-no-return, --warn-redundant-casts, --disallow-incomplete-defs]
